# Generated by Django 5.2.3 on 2025-08-05 17:32

import my_app1.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('profile_photo', models.URLField(blank=True)),
                ('access_token', models.CharField(blank=True, max_length=500, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('achievement', models.CharField(max_length=500)),
                ('image_url', models.URLField(blank=True)),
                ('assigned', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'achievements',
            },
            bases=(my_app1.mixins.ImageUploadMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=50)),
                ('place_of_work', models.CharField(blank=True, max_length=200)),
                ('time_in_theatre', models.CharField(blank=True, max_length=10)),
                ('favorite_writer', models.JSONField(blank=True, default=list, verbose_name=models.CharField(max_length=250))),
                ('favorite_character', models.JSONField(blank=True, default=list, verbose_name=models.CharField(max_length=250))),
                ('favorite_painter', models.JSONField(blank=True, default=list, verbose_name=models.CharField(max_length=350))),
                ('favorite_film', models.JSONField(blank=True, default=list, verbose_name=models.CharField(max_length=250))),
                ('favorite_piece', models.JSONField(blank=True, default=list, verbose_name=models.CharField(max_length=50))),
                ('favorite_quote', models.CharField(max_length=1000)),
                ('author_quote', models.CharField(max_length=50)),
                ('favorite_song', models.JSONField(blank=True, default=list, verbose_name=models.CharField(max_length=250))),
                ('author_song', models.JSONField(blank=True, default=list, verbose_name=models.CharField(max_length=250))),
                ('perfomances', models.JSONField(blank=True, default=list, verbose_name=models.CharField(max_length=100))),
                ('role_in_perfomances', models.JSONField(blank=True, default=list, verbose_name=models.CharField(max_length=50))),
                ('image_url', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'actors',
            },
            bases=(my_app1.mixins.ImageUploadMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2000)),
                ('age_limit', models.CharField(blank=True, max_length=5, null=True)),
                ('premiere_date', models.DateField(null=True)),
                ('afisha', models.BooleanField(default=True)),
                ('image_url', models.URLField(blank=True)),
                ('archive_image', models.URLField(blank=True, null=True)),
                ('images_list', models.JSONField(blank=True, default=list, verbose_name=models.URLField(null=True))),
            ],
            options={
                'db_table': 'archive',
            },
            bases=(my_app1.mixins.ImageUploadMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DirectorsTheatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=2000)),
                ('perfomances', models.JSONField(blank=True, default=list, verbose_name=models.CharField(max_length=200))),
                ('years', models.JSONField(blank=True, default=list, verbose_name=models.IntegerField())),
                ('team_name', models.JSONField(blank=True, default=list, verbose_name=models.CharField(max_length=300))),
                ('image_url', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'directors_theatre',
            },
            bases=(my_app1.mixins.ImageUploadMixin, models.Model),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=2000)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('is_published', models.BooleanField(blank=True, default=False)),
                ('image_url', models.URLField(blank=True)),
                ('date_publish', models.DateField(blank=True, null=True)),
                ('images_list', models.JSONField(blank=True, default=list, verbose_name=models.URLField(null=True))),
            ],
            options={
                'db_table': 'news',
            },
            bases=(my_app1.mixins.ImageUploadMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Perfomances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=20)),
                ('age_limit', models.CharField(max_length=5)),
                ('duration', models.TimeField(null=True)),
                ('premiere_date', models.DateField(null=True)),
                ('production_team', models.JSONField(blank=True, default=list, verbose_name=models.CharField(max_length=70))),
                ('the_cast', models.JSONField(blank=True, default=list, verbose_name=models.CharField(max_length=50))),
                ('description', models.CharField(max_length=2000)),
                ('afisha', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True)),
                ('performances_image', models.URLField(blank=True, null=True)),
                ('images_list', models.JSONField(blank=True, default=list, verbose_name=models.URLField(null=True))),
                ('ticket_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'perfomances',
            },
            bases=(my_app1.mixins.ImageUploadMixin, models.Model),
        ),
    ]
