# Generated by Django 5.2.3 on 2025-08-05 17:32

import my_app1.mixins
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('profile_photo', models.URLField(blank=True)),
                ('access_token', models.CharField(blank=True, max_length=500, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('achievement', models.CharField(max_length=500)),
                ('image_url', models.URLField(blank=True)),
                ('assigned', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'achievements',
            },
            bases=(my_app1.mixins.ImageUploadMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=50)),
                ('place_of_work', models.CharField(blank=True, max_length=200)),
                ('time_in_theatre', models.CharField(blank=True, max_length=10)),
                ('favorite_writer', django.contrib.postgres.fields.ArrayField(models.CharField(max_length=250), blank=True, default=list, size=None)),
                ('favorite_character', django.contrib.postgres.fields.ArrayField(models.CharField(max_length=250), blank=True, default=list, size=None)),
                ('favorite_painter', django.contrib.postgres.fields.ArrayField(models.CharField(max_length=350), blank=True, default=list, size=None)),
                ('favorite_film', django.contrib.postgres.fields.ArrayField(models.CharField(max_length=250), blank=True, default=list, size=None)),
                ('favorite_piece', django.contrib.postgres.fields.ArrayField(models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('favorite_quote', models.CharField(max_length=1000)),
                ('author_quote', models.CharField(max_length=50)),
                ('favorite_song', django.contrib.postgres.fields.ArrayField(models.CharField(max_length=250), blank=True, default=list, size=None)),
                ('author_song', django.contrib.postgres.fields.ArrayField(models.CharField(max_length=250), blank=True, default=list, size=None)),
                ('perfomances', django.contrib.postgres.fields.ArrayField(models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('role_in_perfomances', django.contrib.postgres.fields.ArrayField(models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('image_url', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'actors',
            },
            bases=(my_app1.mixins.ImageUploadMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2000)),
                ('age_limit', models.CharField(blank=True, max_length=5, null=True)),
                ('premiere_date', models.DateField(null=True)),
                ('afisha', models.BooleanField(default=True)),
                ('image_url', models.URLField(blank=True)),
                ('archive_image', models.URLField(blank=True, null=True)),
                ('images_list', django.contrib.postgres.fields.ArrayField(models.URLField(null=True), blank=True, default=list, size=None)),
            ],
            options={
                'db_table': 'archive',
            },
            bases=(my_app1.mixins.ImageUploadMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DirectorsTheatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=2000)),
                ('perfomances', django.contrib.postgres.fields.ArrayField(models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('years', django.contrib.postgres.fields.ArrayField(models.IntegerField(), blank=True, default=list, size=None)),
                ('team_name', django.contrib.postgres.fields.ArrayField(models.CharField(max_length=300), blank=True, default=list, size=None)),
                ('image_url', models.URLField(blank=True)),
            ],
            options={
                'db_table': 'directors_theatre',
            },
            bases=(my_app1.mixins.ImageUploadMixin, models.Model),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=2000)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('is_published', models.BooleanField(blank=True, default=False)),
                ('image_url', models.URLField(blank=True)),
                ('date_publish', models.DateField(blank=True, null=True)),
                ('images_list', django.contrib.postgres.fields.ArrayField(models.URLField(null=True), blank=True, default=list, size=None)),
            ],
            options={
                'db_table': 'news',
            },
            bases=(my_app1.mixins.ImageUploadMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Perfomances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=20)),
                ('age_limit', models.CharField(max_length=5)),
                ('duration', models.TimeField(null=True)),
                ('premiere_date', models.DateField(null=True)),
                ('production_team', django.contrib.postgres.fields.ArrayField(models.CharField(max_length=70), blank=True, default=list, size=None)),
                ('the_cast', django.contrib.postgres.fields.ArrayField(models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('description', models.CharField(max_length=2000)),
                ('afisha', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True)),
                ('performances_image', models.URLField(blank=True, null=True)),
                ('images_list', django.contrib.postgres.fields.ArrayField(models.URLField(null=True), blank=True, default=list, size=None)),
                ('ticket_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'perfomances',
            },
            bases=(my_app1.mixins.ImageUploadMixin, models.Model),
        ),
    ]
