# Generated by Django 5.2.3 on 2025-08-12 14:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='author_song',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='actors',
            name='favorite_character',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='actors',
            name='favorite_film',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='actors',
            name='favorite_painter',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=350), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='actors',
            name='favorite_piece',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='actors',
            name='favorite_song',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='actors',
            name='favorite_writer',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='actors',
            name='perfomances',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='actors',
            name='role_in_perfomances',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='archive',
            name='images_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(null=True), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='directorstheatre',
            name='perfomances',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='directorstheatre',
            name='team_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='directorstheatre',
            name='years',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='news',
            name='images_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(null=True), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='perfomances',
            name='images_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(null=True), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='perfomances',
            name='production_team',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=70), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='perfomances',
            name='the_cast',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
