# Generated by Django 5.2.3 on 2025-08-12 17:03

import django.contrib.postgres.fields
from django.db import migrations, models


def dedupe_phone_numbers(apps, schema_editor):
    """Make phone_number values unique before the unique constraint is added.

    Existing data can contain duplicate (or blank) phone numbers, which would
    make the AlterField operations below fail when they introduce
    ``unique=True``. We keep the phone on the earliest user (lowest id) and
    clear it on later duplicates. ``phone_number`` is nullable, so this never
    deletes accounts.
    """
    User = apps.get_model('my_app1', 'User')
    seen = set()
    for user in User.objects.order_by('id').iterator():
        phone = (user.phone_number or '').strip()
        if not phone:
            if user.phone_number is not None:
                user.phone_number = None
                user.save(update_fields=['phone_number'])
            continue
        if phone in seen:
            user.phone_number = None
            user.save(update_fields=['phone_number'])
        else:
            seen.add(phone)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0001_initial'),
    ]

    operations = [
        # Make phone_number nullable first so the dedupe step below can clear
        # duplicate values before the unique constraint is added.
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.RunPython(dedupe_phone_numbers, noop),
        migrations.AlterField(
            model_name='actors',
            name='author_song',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='actors',
            name='favorite_character',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='actors',
            name='favorite_film',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='actors',
            name='favorite_painter',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=350), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='actors',
            name='favorite_piece',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='actors',
            name='favorite_song',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='actors',
            name='favorite_writer',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='actors',
            name='perfomances',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='actors',
            name='role_in_perfomances',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='archive',
            name='images_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(null=True), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='directorstheatre',
            name='perfomances',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='directorstheatre',
            name='team_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='directorstheatre',
            name='years',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='news',
            name='images_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(null=True), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='perfomances',
            name='images_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(null=True), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='perfomances',
            name='production_team',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=70), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='perfomances',
            name='the_cast',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
