# Generated by Django 5.2.3 on 2026-06-29 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0002_alter_actors_author_song_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfomances',
            name='roles_propagated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='perfomances',
            name='afisha',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PerformanceShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_datetime', models.DateTimeField()),
                ('ticket_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='my_app1.perfomances')),
            ],
            options={
                'db_table': 'performance_show',
                'ordering': ['show_datetime'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_roles', to='my_app1.actors')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_members', to='my_app1.perfomances')),
            ],
            options={
                'db_table': 'performance_cast',
                'ordering': ['id'],
                'unique_together': {('performance', 'actor', 'role')},
            },
        ),
    ]
