# Generated by Django 5.2.3 on 2025-07-02 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0002_achievements_actors_archive_directorstheatre_news_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Peromances',
            new_name='Perfomances',
        ),
    ]
