# Generated by Django 5.2.3 on 2025-07-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0003_rename_peromances_perfomances'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfomances',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
