# Generated by Django 5.2.3 on 2026-06-29 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0003_perfomances_roles_propagated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfomances',
            name='the_cast',
        ),
    ]
