# Generated by Django 5.2.3 on 2026-07-02 14:53

import re
from datetime import date

from django.db import migrations, models
from django.utils import timezone


def backfill_joined_at(apps, schema_editor):
    """Проставить joined_at существующим актёрам из старого поля time_in_theatre.

    Значение time_in_theatre — это число лет в студии (строка), поэтому
    приблизительная дата прихода = сегодня минус это число лет (день = 1-е
    число текущего месяца).
    """
    Actors = apps.get_model('my_app1', 'Actors')
    today = timezone.localdate()
    for actor in Actors.objects.all().iterator():
        if actor.joined_at:
            continue
        raw = actor.time_in_theatre or ''
        match = re.search(r'\d+', raw)
        years = int(match.group()) if match else 0
        try:
            actor.joined_at = date(today.year - years, today.month, 1)
        except ValueError:
            actor.joined_at = date(today.year - years, today.month, 1)
        actor.save(update_fields=['joined_at'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0005_review_reviewreaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actors',
            name='joined_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='actors',
            name='left_at',
            field=models.DateField(blank=True, null=True),
        ),
        # Бэкфилл joined_at до удаления time_in_theatre.
        migrations.RunPython(backfill_joined_at, noop),
        migrations.RemoveField(
            model_name='actors',
            name='time_in_theatre',
        ),
    ]
