# Generated by Django 5.2.3 on 2025-07-03 12:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0005_alter_actors_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorstheatre',
            name='years',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
