# Generated by Django 5.2.3 on 2025-07-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0006_alter_directorstheatre_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
