# Generated by Django 5.2.3 on 2026-07-02 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0006_actors_joined_left_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='review_exactly_one_target',
        ),
        migrations.AddField(
            model_name='review',
            name='archive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='my_app1.archive'),
        ),
        migrations.AddField(
            model_name='review',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='my_app1.directorstheatre'),
        ),
        migrations.AddField(
            model_name='review',
            name='news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='my_app1.news'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', True), ('archive__isnull', True), ('director__isnull', True), ('news__isnull', True), ('performance__isnull', False)), models.Q(('actor__isnull', False), ('archive__isnull', True), ('director__isnull', True), ('news__isnull', True), ('performance__isnull', True)), models.Q(('actor__isnull', True), ('archive__isnull', True), ('director__isnull', False), ('news__isnull', True), ('performance__isnull', True)), models.Q(('actor__isnull', True), ('archive__isnull', False), ('director__isnull', True), ('news__isnull', True), ('performance__isnull', True)), models.Q(('actor__isnull', True), ('archive__isnull', True), ('director__isnull', True), ('news__isnull', False), ('performance__isnull', True)), _connector='OR'), name='review_exactly_one_target'),
        ),
    ]
