# Generated by Django 5.2.3 on 2025-07-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0008_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
