# Generated by Django 5.2.3 on 2026-07-06 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0008_email_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfomances',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_performances', to='my_app1.directorstheatre'),
        ),
    ]
