# Generated by Django 5.2.3 on 2026-07-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0009_perfomance_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfomances',
            name='production_collective',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='perfomances',
            name='production_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='perfomances',
            name='production_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
