# Generated by Django 5.2.3 on 2026-07-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0010_perfomance_production_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfomances',
            name='director_propagated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
