# Generated by Django 5.2.3 on 2025-07-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0010_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
