# Generated by Django 5.2.3 on 2026-07-08 16:08

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


ENSURE_ACHIEVEMENT_IMAGES_LIST_SQL = """
ALTER TABLE public.achievements
    ADD COLUMN IF NOT EXISTS images_list character varying(500)[];
ALTER TABLE public.achievements
    ALTER COLUMN images_list TYPE character varying(500)[]
    USING images_list::character varying(500)[];
UPDATE public.achievements
SET images_list = ARRAY[]::character varying(500)[]
WHERE images_list IS NULL;
ALTER TABLE public.achievements
    ALTER COLUMN images_list SET NOT NULL;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0011_director_propagated_review_softdelete'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayGreeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'birthday_greeting',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True, default='')),
                ('section', models.CharField(blank=True, default='', max_length=100)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('multiline', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'site_content',
                'ordering': ['section', 'order', 'id'],
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=ENSURE_ACHIEVEMENT_IMAGES_LIST_SQL,
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='achievements',
                    name='images_list',
                    field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=500), blank=True, default=list, size=None),
                ),
            ],
        ),
        migrations.AddField(
            model_name='performancecast',
            name='actor_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='performancecast',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cast_roles', to='my_app1.actors'),
        ),
        migrations.CreateModel(
            name='ActorBirthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='birthday', to='my_app1.actors')),
            ],
            options={
                'db_table': 'actor_birthday',
                'ordering': ['birth_date'],
            },
        ),
    ]
