# Generated by Django 5.2.3 on 2025-07-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0011_alter_user_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
