# Generated by Django 5.2.3 on 2025-07-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0012_fix_access_token_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='image_url',
            field=models.CharField(),
        ),
    ]
