# Generated by Django 5.2.3 on 2025-07-09 13:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0013_alter_actors_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='author_song',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
