# Generated by Django 5.2.3 on 2026-07-09 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0013_seed_site_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='actorbirthday',
            name='director',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birthday', to='my_app1.directorstheatre'),
        ),
        migrations.AddField(
            model_name='performancecast',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cast_roles', to='my_app1.directorstheatre'),
        ),
        migrations.AlterField(
            model_name='actorbirthday',
            name='actor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='birthday', to='my_app1.actors'),
        ),
        migrations.AddConstraint(
            model_name='actorbirthday',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor__isnull', False), ('director__isnull', True)), models.Q(('actor__isnull', True), ('director__isnull', False)), _connector='OR'), name='birthday_exactly_one_person'),
        ),
    ]
