# Generated by Django 5.2.3 on 2025-07-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0014_alter_actors_author_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='author_song',
            field=models.CharField(max_length=30),
        ),
    ]
