# Generated by Django 5.2.3 on 2026-07-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0014_actorbirthday_director_performancecast_director_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VkParserState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_done', models.BooleanField(default=False)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_result', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'db_table': 'vk_parser_state',
            },
        ),
        migrations.CreateModel(
            name='SiteReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, default='Зритель', max_length=120)),
                ('avatar_url', models.URLField(blank=True, default='', max_length=500)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('text', models.TextField()),
                ('review_date', models.DateField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True, default='', max_length=500)),
                ('source', models.CharField(default='vk', max_length=20)),
                ('vk_owner_id', models.BigIntegerField(blank=True, null=True)),
                ('vk_post_id', models.BigIntegerField(blank=True, null=True)),
                ('vk_comment_id', models.BigIntegerField(blank=True, null=True)),
                ('pinned', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'site_review',
                'ordering': ['-review_date', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('vk_comment_id__isnull', False)), fields=('vk_owner_id', 'vk_post_id', 'vk_comment_id'), name='uniq_vk_comment')],
            },
        ),
    ]
