# Generated by Django 5.2.3 on 2025-07-09 14:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0015_alter_actors_author_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='author_song',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
