# Generated by Django 5.2.3 on 2025-07-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0017_news_summary_alter_achievements_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
