# Generated by Django 5.2.3 on 2025-07-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0018_news_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
