# Generated by Django 5.2.3 on 2025-07-12 06:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0019_alter_news_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievements',
            name='image_url',
        ),
        migrations.AddField(
            model_name='achievements',
            name='images_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='archive',
            name='afisha',
            field=models.BooleanField(default=True),
        ),
    ]
