# Generated by Django 5.2.3 on 2025-07-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0020_remove_achievements_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievements',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='achievements',
            name='images_urls',
        ),
        migrations.AddField(
            model_name='achievements',
            name='description',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='achievements',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
