# Generated by Django 5.2.3 on 2025-07-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0021_remove_achievements_achievements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
