# Generated by Django 5.2.3 on 2025-07-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0022_alter_achievements_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievements',
            name='description',
        ),
        migrations.AddField(
            model_name='achievements',
            name='achievement',
            field=models.CharField(default=str, max_length=500),
            preserve_default=False,
        ),
    ]
