# Generated by Django 5.2.3 on 2025-07-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0023_remove_achievements_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='title',
            field=models.CharField(default=str, max_length=100),
            preserve_default=False,
        ),
    ]
