# Generated by Django 5.2.3 on 2025-07-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0024_archive_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfomances',
            name='performances_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
