# Generated by Django 5.2.3 on 2025-07-14 13:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0025_perfomances_performances_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfomances',
            name='images_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(null=True), blank=True, default=list, size=None),
        ),
    ]
