# Generated by Django 5.2.3 on 2025-07-16 12:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0026_perfomances_images_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='images_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(null=True), blank=True, default=list, size=None),
        ),
    ]
