# Generated by Django 5.2.3 on 2025-07-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0028_news_date_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfomances',
            name='ticket_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
