# Generated by Django 5.2.3 on 2025-07-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0030_archive_archive_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='age_limit',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
