# Generated by Django 5.2.3 on 2025-07-18 11:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0031_archive_age_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='images_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(null=True), blank=True, default=list, size=None),
        ),
    ]
