# Generated by Django 5.2.3 on 2025-07-20 05:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0032_archive_images_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='author_song',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='actors',
            name='favorite_song',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, default=list, size=None),
        ),
    ]
