# Generated by Django 5.2.3 on 2025-07-20 05:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0034_alter_actors_favorite_painter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='favorite_painter',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=350), blank=True, default=list, size=None),
        ),
    ]
