# Generated by Django 5.2.3 on 2025-07-20 05:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0035_alter_actors_favorite_painter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='favorite_character',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), blank=True, default=list, size=None),
        ),
    ]
