# Generated by Django 5.2.3 on 2025-07-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0037_alter_actors_favorite_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.URLField(blank=True),
        ),
    ]
