# Generated by Django 5.2.3 on 2025-07-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app1', '0038_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='assigned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
